// Generated by scripts/build-photo-displays.py. Do not edit by hand.
window.TRAVEL_LOG_PHOTO_SIZES = Object.freeze({
  "./trip_images/Japan_2026/hnd.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/kitakyushu/blue-wing-moji.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/kitakyushu/fuk-coffee.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/kitakyushu/fuk.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/kitakyushu/kanmon-tunnel.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/kitakyushu/kanmon-tunnel2.webp": {
    "width": 1920,
    "height": 1440
  },
  "./trip_images/Japan_2026/kitakyushu/kokura-castle.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/kitakyushu/mitsubachi-kobo-hana-no-michi-yanagawa.webp": {
    "width": 1187,
    "height": 1920
  },
  "./trip_images/Japan_2026/kitakyushu/mojiko-building.webp": {
    "width": 1920,
    "height": 1440
  },
  "./trip_images/Japan_2026/kitakyushu/mojiko-ferry-1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/kitakyushu/mojiko-ferry-2.webp": {
    "width": 1920,
    "height": 1440
  },
  "./trip_images/Japan_2026/kitakyushu/mojiko-ferry-3.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/kitakyushu/mojiko.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/kitakyushu/nakasu.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/kitakyushu/rx-93ff-nu-gundam-1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/kitakyushu/rx-93ff-nu-gundam-2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/kyoto/kinkaku-ji-1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/kyoto/kinkaku-ji-2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/kyoto/kinkaku-ji-3.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/kyoto/kiyomizu-street1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/kyoto/kiyomizu-street2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/kyoto/kiyomizu1.webp": {
    "width": 1920,
    "height": 1440
  },
  "./trip_images/Japan_2026/kyoto/kiyomizu2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/benzaiten-osu.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/doctor-yellow.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/flight-of-dreams-1.webp": {
    "width": 1920,
    "height": 1440
  },
  "./trip_images/Japan_2026/nagoya/flight-of-dreams-2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/flight-of-dreams-3.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/hitsumabushi-hanaoka-1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/hitsumabushi-hanaoka-2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/inuyama1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/inuyama2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/inuyama3.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/inuyama4.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/kawase-nagoya-1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/kawase-nagoya-2.webp": {
    "width": 1560,
    "height": 1440
  },
  "./trip_images/Japan_2026/nagoya/konparu-osu.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/maruya-honten-centrair-1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/maruya-honten-centrair-2.webp": {
    "width": 1920,
    "height": 1440
  },
  "./trip_images/Japan_2026/nagoya/misokatsu-yabaton-nagoya-castle.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/miyakishimen-jingu.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/nagoya-castle.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/nagoya-castle2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/nagoya-castle3.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/nana-chan.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/nikubei-honten-inuyama-1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/nikubei-honten-inuyama-2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/oasis.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/toyota-building.webp": {
    "width": 1920,
    "height": 1440
  },
  "./trip_images/Japan_2026/nagoya/toyota-car.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/nagoya/toyota-entrance.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/osaka/dotonbori.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/osaka/osaka-castle-map.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/osaka/osaka-castle.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/osaka/osaka-castle1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/osaka/osaka-castle2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/osaka/osaka-castle3.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/osaka/tsutenkaku1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/osaka/tsutenkaku2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sapporo/aji-no-sanpei-1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sapporo/aji-no-sanpei-2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sapporo/beer-museum-pot.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sapporo/beer-museum.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sapporo/clock-tower.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sapporo/red-brick-building.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sapporo/sapporo-beer.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sapporo/sapporo-factory.webp": {
    "width": 1920,
    "height": 1440
  },
  "./trip_images/Japan_2026/sapporo/sapporo-tv-tower.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sapporo/suage-plus.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sdj.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/gyutan-kaku-brandome-1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/gyutan-kaku-brandome-2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/gyutan-kaku-brandome-3.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/gyutan-no-issen-1.webp": {
    "width": 1920,
    "height": 1440
  },
  "./trip_images/Japan_2026/sendai/gyutan-no-issen-2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/gyutan-no-issen-3.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/jozenji-dori.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/jukusei-tonkatsu-furaiya.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/matsushima.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/matsushima1.webp": {
    "width": 1920,
    "height": 1440
  },
  "./trip_images/Japan_2026/sendai/matsushima2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/matsushima3.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/sendai-castle-ruins-wall.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/sendai-castle-ruins.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/sendai-tour-bus.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/umami-tasuke.webp": {
    "width": 1920,
    "height": 1440
  },
  "./trip_images/Japan_2026/sendai/yamadera1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/yamadera2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/yamadera3.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/yamadera4.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/zuihoden1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/zuihoden2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/zuihoden3.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/sendai/zuihoden4.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/ameyayokocho.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/divercity-gundam1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/divercity-gundam2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/ginza-hachigou-1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/ginza-hachigou-2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/ginza-haruchan-ramen.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/harbs-azabudai-hills.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/jal-museum1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/jal-museum2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/kaminarimon.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/meiji-jingu.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/peter-luger-steak-house-tokyo-1.webp": {
    "width": 1920,
    "height": 1906
  },
  "./trip_images/Japan_2026/tokyo/peter-luger-steak-house-tokyo-2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/shibuya-crossing.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/shibuya-crossing2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/shibuya-crossing3.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/statue-of-liberty.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/teamlab1.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/teamlab2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/teamlab3.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/teamlab4.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/teamlab5.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/tokyo-skytree.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/tokyo-tower-day.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/tokyo-tower-night.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/tokyo/tokyo-tower-night2.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Japan_2026/yyz.webp": {
    "width": 1440,
    "height": 1920
  },
  "./trip_images/Quebec_2025/montreal/amphitrite.jpeg": {
    "width": 3213,
    "height": 5712
  },
  "./trip_images/Quebec_2025/montreal/monarque.jpeg": {
    "width": 3024,
    "height": 4032
  },
  "./trip_images/Quebec_2025/montreal/mount_royal_chalet.jpeg": {
    "width": 2268,
    "height": 4032
  },
  "./trip_images/Quebec_2025/montreal/old_port.jpeg": {
    "width": 3213,
    "height": 5712
  },
  "./trip_images/Quebec_2025/montreal/oratory.jpeg": {
    "width": 2268,
    "height": 4032
  },
  "./trip_images/Quebec_2025/montreal/the_ring.jpeg": {
    "width": 2268,
    "height": 4032
  },
  "./trip_images/Quebec_2025/quebec_city/fairmount_frontenac_day.jpeg": {
    "width": 4536,
    "height": 8064
  },
  "./trip_images/Quebec_2025/quebec_city/fairmount_frontenac_night.jpeg": {
    "width": 3213,
    "height": 5712
  },
  "./trip_images/Quebec_2025/quebec_city/rue_du_petit-champlain.jpeg": {
    "width": 2268,
    "height": 4032
  },
  "./trip_images/Quebec_2026/montreal/old_port.jpg": {
    "width": 3024,
    "height": 4032
  },
  "./trip_images/Quebec_2026/montreal/the_ring.jpg": {
    "width": 3024,
    "height": 4032
  },
  "./trip_images/Quebec_2026/saint_sauveur/billboard.jpeg": {
    "width": 2850,
    "height": 3800
  },
  "./trip_images/Quebec_2026/saint_sauveur/lift.jpg": {
    "width": 3024,
    "height": 4032
  }
});
